/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __DRIVER_I2C_H__
#define __DRIVER_I2C_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <hwf4/i2c.h>
#include <ivory.h>

#ifdef __cplusplus
}
#endif
#endif /* __DRIVER_I2C_H__ */