/* This file has been autogenerated by Ivory
 * Compiler version  b48fa4470fb0630f5faec99220f1a507651451af
 */
#ifndef __IVORY_FLOAT_HELPER_H__
#define __IVORY_FLOAT_HELPER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>

#ifdef __cplusplus
}
#endif
#endif /* __IVORY_FLOAT_HELPER_H__ */