/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __IVORY_STRING_H__
#define __IVORY_STRING_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include <smaccmpilot/ivory_string_prim.h>
#include <string.h>

#ifdef __cplusplus
}
#endif
#endif /* __IVORY_STRING_H__ */