/* This file has been autogenerated by Ivory
 * Compiler version  b48fa4470fb0630f5faec99220f1a507651451af
 */
#ifndef __SENSORS_TYPE_H__
#define __SENSORS_TYPE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
struct sensors_result {
    bool valid;
    float roll;
    float pitch;
    float yaw;
    float omega_x;
    float omega_y;
    float omega_z;
    float baro_alt;
    float xacc;
    float yacc;
    float zacc;
    uint32_t time;
};

#ifdef __cplusplus
}
#endif
#endif /* __SENSORS_TYPE_H__ */