/* This file has been autogenerated by Ivory
 * Compiler version  b48fa4470fb0630f5faec99220f1a507651451af
 */
#ifndef __SERVO_TYPE_H__
#define __SERVO_TYPE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
struct servo_result {
    bool valid;
    uint16_t servo[4U];
    uint32_t time;
};

#ifdef __cplusplus
}
#endif
#endif /* __SERVO_TYPE_H__ */