/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __STORAGE_EEPROM_H__
#define __STORAGE_EEPROM_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include "driver_i2c.h"

#ifdef __cplusplus
}
#endif
#endif /* __STORAGE_EEPROM_H__ */