/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __USERINPUT_DECODE_H__
#define __USERINPUT_DECODE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include "userinput_type.h"
struct userinput_decode_state {
    uint16_t last_modepwm;
    uint32_t last_modepwm_time;
    uint8_t arm_state;
    uint32_t arm_state_time;
};
void userinput_decode(uint16_t n_var0[8U],
                      struct userinput_decode_state* n_var1,
                      struct userinput_result* n_var2, uint32_t n_var3);
float userinput_scale(uint16_t n_var0, uint16_t n_var1, float n_var2,
                      float n_var3, uint16_t n_var4);

#ifdef __cplusplus
}
#endif
#endif /* __USERINPUT_DECODE_H__ */