/* This file has been autogenerated by Ivory
 * Compiler version  5326f414a5a63af59269d31f823a2e142af0b2c9
 */
#ifndef __USERINPUT_TYPE_H__
#define __USERINPUT_TYPE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
struct userinput_result {
    bool armed;
    float throttle;
    float roll;
    float pitch;
    float yaw;
    uint32_t time;
};

#ifdef __cplusplus
}
#endif
#endif /* __USERINPUT_TYPE_H__ */