{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavlink_ivory.py

module SMACCMPilot.Mavlink.Messages.SetLocalPositionSetpoint where

import SMACCMPilot.Mavlink.Pack
import SMACCMPilot.Mavlink.Unpack
import SMACCMPilot.Mavlink.Send

import Ivory.Language

setLocalPositionSetpointMsgId :: Uint8
setLocalPositionSetpointMsgId = 50

setLocalPositionSetpointCrcExtra :: Uint8
setLocalPositionSetpointCrcExtra = 214

setLocalPositionSetpointModule :: Module
setLocalPositionSetpointModule = package "mavlink_set_local_position_setpoint_msg" $ do
  depend packModule
  incl setLocalPositionSetpointUnpack
  defStruct (Proxy :: Proxy "set_local_position_setpoint_msg")

[ivory|
struct set_local_position_setpoint_msg
  { x :: Stored IFloat
  ; y :: Stored IFloat
  ; z :: Stored IFloat
  ; yaw :: Stored IFloat
  ; target_system :: Stored Uint8
  ; target_component :: Stored Uint8
  ; coordinate_frame :: Stored Uint8
  }
|]

mkSetLocalPositionSetpointSender :: SizedMavlinkSender 19
                       -> Def ('[ ConstRef s (Struct "set_local_position_setpoint_msg") ] :-> ())
mkSetLocalPositionSetpointSender sender =
  proc ("mavlink_set_local_position_setpoint_msg_send" ++ (senderName sender)) $ \msg -> body $ do
    setLocalPositionSetpointPack (senderMacro sender) msg

instance MavlinkSendable "set_local_position_setpoint_msg" 19 where
  mkSender = mkSetLocalPositionSetpointSender

setLocalPositionSetpointPack :: (eff `AllocsIn` s, eff `Returns` ())
                  => SenderMacro eff s 19
                  -> ConstRef s1 (Struct "set_local_position_setpoint_msg")
                  -> Ivory eff ()
setLocalPositionSetpointPack sender msg = do
  arr <- local (iarray [] :: Init (Array 19 (Stored Uint8)))
  let buf = toCArray arr
  call_ pack buf 0 =<< deref (msg ~> x)
  call_ pack buf 4 =<< deref (msg ~> y)
  call_ pack buf 8 =<< deref (msg ~> z)
  call_ pack buf 12 =<< deref (msg ~> yaw)
  call_ pack buf 16 =<< deref (msg ~> target_system)
  call_ pack buf 17 =<< deref (msg ~> target_component)
  call_ pack buf 18 =<< deref (msg ~> coordinate_frame)
  sender setLocalPositionSetpointMsgId (constRef arr) setLocalPositionSetpointCrcExtra
  retVoid

instance MavlinkUnpackableMsg "set_local_position_setpoint_msg" where
    unpackMsg = ( setLocalPositionSetpointUnpack , setLocalPositionSetpointMsgId )

setLocalPositionSetpointUnpack :: Def ('[ Ref s1 (Struct "set_local_position_setpoint_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
setLocalPositionSetpointUnpack = proc "mavlink_set_local_position_setpoint_unpack" $ \ msg buf -> body $ do
  store (msg ~> x) =<< call unpack buf 0
  store (msg ~> y) =<< call unpack buf 4
  store (msg ~> z) =<< call unpack buf 8
  store (msg ~> yaw) =<< call unpack buf 12
  store (msg ~> target_system) =<< call unpack buf 16
  store (msg ~> target_component) =<< call unpack buf 17
  store (msg ~> coordinate_frame) =<< call unpack buf 18

