/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __SMAVLINK_PACK_IVORY_H__
#define __SMAVLINK_PACK_IVORY_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include <smavlink/pack.h>

#ifdef __cplusplus
}
#endif
#endif /* __SMAVLINK_PACK_IVORY_H__ */