/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __SMAVLINK_MESSAGE_MANUAL_CONTROL_H__
#define __SMAVLINK_MESSAGE_MANUAL_CONTROL_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include <smavlink/channel.h>
#include <smavlink/system.h>
#include "smavlink_pack_ivory.h"
struct manual_control_msg {
    int16_t x;
    int16_t y;
    int16_t z;
    int16_t r;
    uint16_t buttons;
    uint8_t target;
};
void smavlink_send_manual_control(struct manual_control_msg* n_var0,
                                  struct smavlink_out_channel* n_var1,
                                  struct smavlink_system* n_var2);
void smavlink_unpack_manual_control(struct manual_control_msg* n_var0, const
                                    uint8_t** n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __SMAVLINK_MESSAGE_MANUAL_CONTROL_H__ */