/* This file has been autogenerated by Ivory
 * Compiler version  5326f414a5a63af59269d31f823a2e142af0b2c9
 */
#ifndef __SMAVLINK_MESSAGE_PARAM_REQUEST_LIST_H__
#define __SMAVLINK_MESSAGE_PARAM_REQUEST_LIST_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include <smavlink/channel.h>
#include <smavlink/system.h>
struct param_request_list_msg {
    uint8_t target_system;
    uint8_t target_component;
};
void smavlink_send_param_request_list(struct param_request_list_msg* n_var0,
                                      struct smavlink_out_channel* n_var1,
                                      struct smavlink_system* n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __SMAVLINK_MESSAGE_PARAM_REQUEST_LIST_H__ */