/* This file has been autogenerated by Ivory
 * Compiler version  Version {versionBranch = [0,1,0,0], versionTags = []}
 */
#ifndef __SMAVLINK_MESSAGE_SYSTEM_TIME_H__
#define __SMAVLINK_MESSAGE_SYSTEM_TIME_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include <smavlink/channel.h>
#include <smavlink/system.h>
struct system_time_msg {
    uint64_t time_unix_usec;
    uint32_t time_boot_ms;
};
void smavlink_send_system_time(struct system_time_msg* n_var0,
                               struct smavlink_out_channel* n_var1,
                               struct smavlink_system* n_var2);
void smavlink_unpack_system_time(struct system_time_msg* n_var0, const
                                 uint8_t** n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __SMAVLINK_MESSAGE_SYSTEM_TIME_H__ */