/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __IVORY_HW_H__
#define __IVORY_HW_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory.h>
#include <ivory_hw_prim.h>

#ifdef __cplusplus
}
#endif
#endif /* __IVORY_HW_H__ */