{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Ivory.Messages.Data32 where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Ivory.Send
import SMACCMPilot.Mavlink.Ivory.Unpack

data32MsgId :: Uint8
data32MsgId = 170

data32CrcExtra :: Uint8
data32CrcExtra = 240

data32Module :: Module
data32Module = package "mavlink_data32_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkData32Sender
  incl data32Unpack
  defStruct (Proxy :: Proxy "data32_msg")
  wrappedPackMod data32Wrapper

[ivory|
struct data32_msg
  { data32_type :: Stored Uint8
  ; len :: Stored Uint8
  ; data32 :: Array 32 (Stored Uint8)
  }
|]

mkData32Sender ::
  Def ('[ ConstRef s0 (Struct "data32_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkData32Sender = makeMavlinkSender "data32_msg" data32MsgId data32CrcExtra

instance MavlinkUnpackableMsg "data32_msg" where
    unpackMsg = ( data32Unpack , data32MsgId )

data32Unpack :: Def ('[ Ref s1 (Struct "data32_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
data32Unpack = proc "mavlink_data32_unpack" $ \ msg buf -> body $ packGet packRep buf 0 msg

data32Wrapper :: WrappedPackRep (Struct "data32_msg")
data32Wrapper = wrapPackRep "mavlink_data32" $ packStruct
  [ packLabel data32_type
  , packLabel len
  , packLabel data32
  ]

instance Packable (Struct "data32_msg") where
  packRep = wrappedPackRep data32Wrapper
