{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.LocalPositionNed where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Send
import SMACCMPilot.Mavlink.Unpack

localPositionNedMsgId :: Uint8
localPositionNedMsgId = 32

localPositionNedCrcExtra :: Uint8
localPositionNedCrcExtra = 185

localPositionNedModule :: Module
localPositionNedModule = package "mavlink_local_position_ned_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkLocalPositionNedSender
  incl localPositionNedUnpack
  defStruct (Proxy :: Proxy "local_position_ned_msg")
  wrappedPackMod localPositionNedWrapper

[ivory|
struct local_position_ned_msg
  { time_boot_ms :: Stored Uint32
  ; x :: Stored IFloat
  ; y :: Stored IFloat
  ; z :: Stored IFloat
  ; vx :: Stored IFloat
  ; vy :: Stored IFloat
  ; vz :: Stored IFloat
  }
|]

mkLocalPositionNedSender ::
  Def ('[ ConstRef s0 (Struct "local_position_ned_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkLocalPositionNedSender = makeMavlinkSender "local_position_ned_msg" localPositionNedMsgId localPositionNedCrcExtra

instance MavlinkUnpackableMsg "local_position_ned_msg" where
    unpackMsg = ( localPositionNedUnpack , localPositionNedMsgId )

localPositionNedUnpack :: Def ('[ Ref s1 (Struct "local_position_ned_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
localPositionNedUnpack = proc "mavlink_local_position_ned_unpack" $ \ msg buf -> body $ packGet packRep buf 0 msg

localPositionNedWrapper :: WrappedPackRep (Struct "local_position_ned_msg")
localPositionNedWrapper = wrapPackRep "mavlink_local_position_ned" $ packStruct
  [ packLabel time_boot_ms
  , packLabel x
  , packLabel y
  , packLabel z
  , packLabel vx
  , packLabel vy
  , packLabel vz
  ]

instance Packable (Struct "local_position_ned_msg") where
  packRep = wrappedPackRep localPositionNedWrapper
