{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Ivory.Messages.MissionRequestPartialList where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Ivory.Send
import SMACCMPilot.Mavlink.Ivory.Unpack

missionRequestPartialListMsgId :: Uint8
missionRequestPartialListMsgId = 37

missionRequestPartialListCrcExtra :: Uint8
missionRequestPartialListCrcExtra = 212

missionRequestPartialListModule :: Module
missionRequestPartialListModule = package "mavlink_mission_request_partial_list_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkMissionRequestPartialListSender
  incl missionRequestPartialListUnpack
  defStruct (Proxy :: Proxy "mission_request_partial_list_msg")
  wrappedPackMod missionRequestPartialListWrapper

[ivory|
struct mission_request_partial_list_msg
  { start_index :: Stored Sint16
  ; end_index :: Stored Sint16
  ; target_system :: Stored Uint8
  ; target_component :: Stored Uint8
  }
|]

mkMissionRequestPartialListSender ::
  Def ('[ ConstRef s0 (Struct "mission_request_partial_list_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkMissionRequestPartialListSender = makeMavlinkSender "mission_request_partial_list_msg" missionRequestPartialListMsgId missionRequestPartialListCrcExtra

instance MavlinkUnpackableMsg "mission_request_partial_list_msg" where
    unpackMsg = ( missionRequestPartialListUnpack , missionRequestPartialListMsgId )

missionRequestPartialListUnpack :: Def ('[ Ref s1 (Struct "mission_request_partial_list_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
missionRequestPartialListUnpack = proc "mavlink_mission_request_partial_list_unpack" $ \ msg buf -> body $ packGet packRep buf 0 msg

missionRequestPartialListWrapper :: WrappedPackRep (Struct "mission_request_partial_list_msg")
missionRequestPartialListWrapper = wrapPackRep "mavlink_mission_request_partial_list" $ packStruct
  [ packLabel start_index
  , packLabel end_index
  , packLabel target_system
  , packLabel target_component
  ]

instance Packable (Struct "mission_request_partial_list_msg") where
  packRep = wrappedPackRep missionRequestPartialListWrapper
