{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Ivory.Messages.ParamRequestList where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Ivory.Send
import SMACCMPilot.Mavlink.Ivory.Unpack

paramRequestListMsgId :: Uint8
paramRequestListMsgId = 21

paramRequestListCrcExtra :: Uint8
paramRequestListCrcExtra = 159

paramRequestListModule :: Module
paramRequestListModule = package "mavlink_param_request_list_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkParamRequestListSender
  incl paramRequestListUnpack
  defStruct (Proxy :: Proxy "param_request_list_msg")
  wrappedPackMod paramRequestListWrapper

[ivory|
struct param_request_list_msg
  { target_system :: Stored Uint8
  ; target_component :: Stored Uint8
  }
|]

mkParamRequestListSender ::
  Def ('[ ConstRef s0 (Struct "param_request_list_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkParamRequestListSender = makeMavlinkSender "param_request_list_msg" paramRequestListMsgId paramRequestListCrcExtra

instance MavlinkUnpackableMsg "param_request_list_msg" where
    unpackMsg = ( paramRequestListUnpack , paramRequestListMsgId )

paramRequestListUnpack :: Def ('[ Ref s1 (Struct "param_request_list_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
paramRequestListUnpack = proc "mavlink_param_request_list_unpack" $ \ msg buf -> body $ packGet packRep buf 0 msg

paramRequestListWrapper :: WrappedPackRep (Struct "param_request_list_msg")
paramRequestListWrapper = wrapPackRep "mavlink_param_request_list" $ packStruct
  [ packLabel target_system
  , packLabel target_component
  ]

instance Packable (Struct "param_request_list_msg") where
  packRep = wrappedPackRep paramRequestListWrapper
