{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Ivory.Messages.SystemTime where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Ivory.Send
import SMACCMPilot.Mavlink.Ivory.Unpack

systemTimeMsgId :: Uint8
systemTimeMsgId = 2

systemTimeCrcExtra :: Uint8
systemTimeCrcExtra = 137

systemTimeModule :: Module
systemTimeModule = package "mavlink_system_time_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkSystemTimeSender
  incl systemTimeUnpack
  defStruct (Proxy :: Proxy "system_time_msg")
  wrappedPackMod systemTimeWrapper

[ivory|
struct system_time_msg
  { time_unix_usec :: Stored Uint64
  ; time_boot_ms :: Stored Uint32
  }
|]

mkSystemTimeSender ::
  Def ('[ ConstRef s0 (Struct "system_time_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkSystemTimeSender = makeMavlinkSender "system_time_msg" systemTimeMsgId systemTimeCrcExtra

instance MavlinkUnpackableMsg "system_time_msg" where
    unpackMsg = ( systemTimeUnpack , systemTimeMsgId )

systemTimeUnpack :: Def ('[ Ref s1 (Struct "system_time_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
systemTimeUnpack = proc "mavlink_system_time_unpack" $ \ msg buf -> body $ packGet packRep buf 0 msg

systemTimeWrapper :: WrappedPackRep (Struct "system_time_msg")
systemTimeWrapper = wrapPackRep "mavlink_system_time" $ packStruct
  [ packLabel time_unix_usec
  , packLabel time_boot_ms
  ]

instance Packable (Struct "system_time_msg") where
  packRep = wrappedPackRep systemTimeWrapper
