
IVORY_BSP_STM32F4_GEN_DIR   := $(TOP)/bsp/ivory/tests/ledblink
IVORY_BSP_STM32F4_SANDBOX   := $(TOP)/../dsl/cabal-dev
IVORY_BSP_STM32F4_GEN_PROG  := ledblink-gen
IVORY_BSP_STM32F4_GEN_EXEC  := $(TOP)/bsp/ivory/ivory-bsp-stm32f4/dist/build/$(IVORY_BSP_STM32F4_GEN_PROG)/$(IVORY_BSP_STM32F4_GEN_PROG)
IVORY_BSP_STM32F4_GEN_DEPS  := $(IVORY_BSP_STM32F4_GEN_DIR)/dep.mk

-include $(IVORY_BSP_STM32F4_GEN_DEPS)

IVORY += ivory-bsp-stm32f4-build

.PHONY: ivory-bsp-stm32f4-build
ivory-bsp-stm32f4-build: $(IVORY_BSP_STM32F4_GEN_EXEC) $(IVORY_BSP_STM32F4_HEADERS) $(IVORY_BSP_STM32F4_SOURCES)

$(IVORY_BSP_STM32F4_GEN_DEPS): $(IVORY_BSP_STM32F4_SANDBOX)/bin/$(IVORY_BSP_STM32F4_GEN_PROG)
	$(IVORY_BSP_STM32F4_SANDBOX)/bin/$(IVORY_BSP_STM32F4_GEN_PROG) \
	  --src-dir=$(IVORY_BSP_STM32F4_GEN_DIR) \
	  --include-dir=$(IVORY_BSP_STM32F4_GEN_DIR) \
	  --deps=$(IVORY_BSP_STM32F4_GEN_DEPS) \
	  --dep-prefix=IVORY_BSP_STM32F4

$(IVORY_BSP_STM32F4_HEADERS) $(IVORY_BSP_STM32F4_SOURCES): $(IVORY_BSP_STM32F4_GEN_DEPS)
	$(IVORY_BSP_STM32F4_SANDBOX)/bin/$(IVORY_BSP_STM32F4_GEN_PROG) \
	  --src-dir=$(IVORY_BSP_STM32F4_GEN_DIR) \
	  --include-dir=$(IVORY_BSP_STM32F4_GEN_DIR) \
	  $(IVORY_OPTS)

.PRECIOUS: $(IVORY_BSP_STM32F4_GEN_EXEC)
$(IVORY_BSP_STM32F4_GEN_EXEC):
	cabal-dev -s $(IVORY_BSP_STM32F4_SANDBOX) install --builddir=$(TOP)/bsp/ivory/ivory-bsp-stm32f4 \
	          $(TOP)/bsp/ivory/ivory-bsp-stm32f4

