/* This file has been autogenerated by Ivory
 * Compiler version  5326f414a5a63af59269d31f823a2e142af0b2c9
 */
#include <out.h>
#include <smavlink/pack.h>
#include "smavlink_message_gps_raw_int.h"
void smavlink_send_gps_raw_int(struct gps_raw_int_msg* n_var0,
                               struct smavlink_out_channel* n_var1,
                               struct smavlink_system* n_var2)
{
    uint8_t n_local0[30U] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t(* n_ref1)[30U] = &n_local0;
    uint64_t n_deref2 = *&n_var0->time_usec;
    
    smavlink_pack_uint64_t(n_ref1, 0U, n_deref2);
    
    int32_t n_deref3 = *&n_var0->lat;
    
    smavlink_pack_int32_t(n_ref1, 8U, n_deref3);
    
    int32_t n_deref4 = *&n_var0->lon;
    
    smavlink_pack_int32_t(n_ref1, 12U, n_deref4);
    
    int32_t n_deref5 = *&n_var0->alt;
    
    smavlink_pack_int32_t(n_ref1, 16U, n_deref5);
    
    uint16_t n_deref6 = *&n_var0->eph;
    
    smavlink_pack_uint16_t(n_ref1, 20U, n_deref6);
    
    uint16_t n_deref7 = *&n_var0->epv;
    
    smavlink_pack_uint16_t(n_ref1, 22U, n_deref7);
    
    uint16_t n_deref8 = *&n_var0->vel;
    
    smavlink_pack_uint16_t(n_ref1, 24U, n_deref8);
    
    uint16_t n_deref9 = *&n_var0->cog;
    
    smavlink_pack_uint16_t(n_ref1, 26U, n_deref9);
    
    uint8_t n_deref10 = *&n_var0->fix_type;
    
    smavlink_pack_uint8_t(n_ref1, 28U, n_deref10);
    
    uint8_t n_deref11 = *&n_var0->satellites_visible;
    
    smavlink_pack_uint8_t(n_ref1, 29U, n_deref11);
    smavlink_send_ivory(n_var1, n_var2, 24U, n_ref1, 30U, 24U);
    return;
}
