/* This file has been autogenerated by Ivory
 * Compiler version  Version {versionBranch = [0,1,0,0], versionTags = []}
 */
#include <smavlink/pack.h>
#include "smavlink_message_setpoint_8dof.h"
void smavlink_send_setpoint_8dof(struct setpoint_8dof_msg* n_var0,
                                 struct smavlink_out_channel* n_var1,
                                 struct smavlink_system* n_var2)
{
    uint8_t n_local0[33U] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t(* n_ref1)[33U] = &n_local0;
    float n_deref2 = *&n_var0->val1;
    
    smavlink_pack_float(n_ref1, 0U, n_deref2);
    
    float n_deref3 = *&n_var0->val2;
    
    smavlink_pack_float(n_ref1, 4U, n_deref3);
    
    float n_deref4 = *&n_var0->val3;
    
    smavlink_pack_float(n_ref1, 8U, n_deref4);
    
    float n_deref5 = *&n_var0->val4;
    
    smavlink_pack_float(n_ref1, 12U, n_deref5);
    
    float n_deref6 = *&n_var0->val5;
    
    smavlink_pack_float(n_ref1, 16U, n_deref6);
    
    float n_deref7 = *&n_var0->val6;
    
    smavlink_pack_float(n_ref1, 20U, n_deref7);
    
    float n_deref8 = *&n_var0->val7;
    
    smavlink_pack_float(n_ref1, 24U, n_deref8);
    
    float n_deref9 = *&n_var0->val8;
    
    smavlink_pack_float(n_ref1, 28U, n_deref9);
    
    uint8_t n_deref10 = *&n_var0->target_system;
    
    smavlink_pack_uint8_t(n_ref1, 32U, n_deref10);
    smavlink_send_ivory(n_var1, n_var2, 148U, n_ref1, 33U, 241U);
    return;
}
void smavlink_unpack_setpoint_8dof(struct setpoint_8dof_msg* n_var0, const
                                   uint8_t** n_var1)
{
    float n_r0 = smavlink_unpack_float(n_var1, 0U);
    
    *&n_var0->val1 = n_r0;
    
    float n_r1 = smavlink_unpack_float(n_var1, 4U);
    
    *&n_var0->val2 = n_r1;
    
    float n_r2 = smavlink_unpack_float(n_var1, 8U);
    
    *&n_var0->val3 = n_r2;
    
    float n_r3 = smavlink_unpack_float(n_var1, 12U);
    
    *&n_var0->val4 = n_r3;
    
    float n_r4 = smavlink_unpack_float(n_var1, 16U);
    
    *&n_var0->val5 = n_r4;
    
    float n_r5 = smavlink_unpack_float(n_var1, 20U);
    
    *&n_var0->val6 = n_r5;
    
    float n_r6 = smavlink_unpack_float(n_var1, 24U);
    
    *&n_var0->val7 = n_r6;
    
    float n_r7 = smavlink_unpack_float(n_var1, 28U);
    
    *&n_var0->val8 = n_r7;
    
    uint8_t n_r8 = smavlink_unpack_uint8_t(n_var1, 32U);
    
    *&n_var0->target_system = n_r8;
}
