/* This file has been autogenerated by Ivory
 * Compiler version  5326f414a5a63af59269d31f823a2e142af0b2c9
 */
#include <out.h>
#include <smavlink/pack.h>
#include "smavlink_message_setpoint_6dof.h"
void smavlink_send_setpoint_6dof(struct setpoint_6dof_msg* n_var0,
                                 struct smavlink_out_channel* n_var1,
                                 struct smavlink_system* n_var2)
{
    uint8_t n_local0[25U] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                             0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t(* n_ref1)[25U] = &n_local0;
    float n_deref2 = *&n_var0->trans_x;
    
    smavlink_pack_float(n_ref1, 0U, n_deref2);
    
    float n_deref3 = *&n_var0->trans_y;
    
    smavlink_pack_float(n_ref1, 4U, n_deref3);
    
    float n_deref4 = *&n_var0->trans_z;
    
    smavlink_pack_float(n_ref1, 8U, n_deref4);
    
    float n_deref5 = *&n_var0->rot_x;
    
    smavlink_pack_float(n_ref1, 12U, n_deref5);
    
    float n_deref6 = *&n_var0->rot_y;
    
    smavlink_pack_float(n_ref1, 16U, n_deref6);
    
    float n_deref7 = *&n_var0->rot_z;
    
    smavlink_pack_float(n_ref1, 20U, n_deref7);
    
    uint8_t n_deref8 = *&n_var0->target_system;
    
    smavlink_pack_uint8_t(n_ref1, 24U, n_deref8);
    smavlink_send_ivory(n_var1, n_var2, 149U, n_ref1, 25U, 15U);
    return;
}
