/* This file has been autogenerated by Ivory
 * Compiler version  Version {versionBranch = [0,1,0,0], versionTags = []}
 */
#include <smavlink/pack.h>
#include "smavlink_message_rc_channels_raw.h"
void smavlink_send_rc_channels_raw(struct rc_channels_raw_msg* n_var0,
                                   struct smavlink_out_channel* n_var1,
                                   struct smavlink_system* n_var2)
{
    uint8_t n_local0[22U] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                             0, 0, 0, 0, 0};
    uint8_t* n_ref1 = n_local0;
    uint32_t n_deref2 = *&n_var0->time_boot_ms;
    
    smavlink_pack_uint32_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint16_t n_deref3 = *&n_var0->chan1_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 4U, n_deref3);
    
    uint16_t n_deref4 = *&n_var0->chan2_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 6U, n_deref4);
    
    uint16_t n_deref5 = *&n_var0->chan3_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 8U, n_deref5);
    
    uint16_t n_deref6 = *&n_var0->chan4_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 10U, n_deref6);
    
    uint16_t n_deref7 = *&n_var0->chan5_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 12U, n_deref7);
    
    uint16_t n_deref8 = *&n_var0->chan6_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 14U, n_deref8);
    
    uint16_t n_deref9 = *&n_var0->chan7_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 16U, n_deref9);
    
    uint16_t n_deref10 = *&n_var0->chan8_raw;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 18U, n_deref10);
    
    uint8_t n_deref11 = *&n_var0->port;
    
    smavlink_pack_uint8_t((uint8_t*) n_ref1, 20U, n_deref11);
    
    uint8_t n_deref12 = *&n_var0->rssi;
    
    smavlink_pack_uint8_t((uint8_t*) n_ref1, 21U, n_deref12);
    smavlink_send_ivory(n_var1, n_var2, 35U, (uint8_t*) n_ref1, 22U, 244U);
    return;
}
void smavlink_unpack_rc_channels_raw(struct rc_channels_raw_msg* n_var0, const
                                     uint8_t** n_var1)
{
    uint32_t n_r0 = smavlink_unpack_uint32_t(n_var1, 0U);
    
    *&n_var0->time_boot_ms = n_r0;
    
    uint16_t n_r1 = smavlink_unpack_uint16_t(n_var1, 4U);
    
    *&n_var0->chan1_raw = n_r1;
    
    uint16_t n_r2 = smavlink_unpack_uint16_t(n_var1, 6U);
    
    *&n_var0->chan2_raw = n_r2;
    
    uint16_t n_r3 = smavlink_unpack_uint16_t(n_var1, 8U);
    
    *&n_var0->chan3_raw = n_r3;
    
    uint16_t n_r4 = smavlink_unpack_uint16_t(n_var1, 10U);
    
    *&n_var0->chan4_raw = n_r4;
    
    uint16_t n_r5 = smavlink_unpack_uint16_t(n_var1, 12U);
    
    *&n_var0->chan5_raw = n_r5;
    
    uint16_t n_r6 = smavlink_unpack_uint16_t(n_var1, 14U);
    
    *&n_var0->chan6_raw = n_r6;
    
    uint16_t n_r7 = smavlink_unpack_uint16_t(n_var1, 16U);
    
    *&n_var0->chan7_raw = n_r7;
    
    uint16_t n_r8 = smavlink_unpack_uint16_t(n_var1, 18U);
    
    *&n_var0->chan8_raw = n_r8;
    
    uint8_t n_r9 = smavlink_unpack_uint8_t(n_var1, 20U);
    
    *&n_var0->port = n_r9;
    
    uint8_t n_r10 = smavlink_unpack_uint8_t(n_var1, 21U);
    
    *&n_var0->rssi = n_r10;
}
