/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "smavlink_message_command_ack.h"
void smavlink_send_command_ack(struct command_ack_msg* n_var0,
                               struct smavlink_out_channel* n_var1,
                               struct smavlink_system* n_var2)
{
    uint8_t n_local0[3U] = {0};
    uint8_t* n_ref1 = n_local0;
    uint16_t n_deref2 = *&n_var0->command;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint8_t n_deref3 = *&n_var0->result;
    
    smavlink_pack_uint8_t((uint8_t*) n_ref1, 2U, n_deref3);
    smavlink_send_ivory(n_var1, n_var2, 77U, (uint8_t*) n_ref1, 3U, 143U);
    return;
}
void smavlink_unpack_command_ack(struct command_ack_msg* n_var0, const
                                 uint8_t* n_var1)
{
    uint16_t n_r0 = smavlink_unpack_uint16_t(n_var1, 0U);
    
    *&n_var0->command = n_r0;
    
    uint8_t n_r1 = smavlink_unpack_uint8_t(n_var1, 2U);
    
    *&n_var0->result = n_r1;
}
