/* This file has been autogenerated by Ivory
 * Compiler version  Version {versionBranch = [0,1,0,0], versionTags = []}
 */
#include <smavlink/pack.h>
#include "smavlink_message_set_global_position_setpoint_int.h"
void smavlink_send_set_global_position_setpoint_int(struct set_global_position_setpoint_int_msg* n_var0,
                                                    struct smavlink_out_channel* n_var1,
                                                    struct smavlink_system* n_var2)
{
    uint8_t n_local0[15U] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t(* n_ref1)[15U] = &n_local0;
    int32_t n_deref2 = *&n_var0->latitude;
    
    smavlink_pack_int32_t(n_ref1, 0U, n_deref2);
    
    int32_t n_deref3 = *&n_var0->longitude;
    
    smavlink_pack_int32_t(n_ref1, 4U, n_deref3);
    
    int32_t n_deref4 = *&n_var0->altitude;
    
    smavlink_pack_int32_t(n_ref1, 8U, n_deref4);
    
    int16_t n_deref5 = *&n_var0->yaw;
    
    smavlink_pack_int16_t(n_ref1, 12U, n_deref5);
    
    uint8_t n_deref6 = *&n_var0->coordinate_frame;
    
    smavlink_pack_uint8_t(n_ref1, 14U, n_deref6);
    smavlink_send_ivory(n_var1, n_var2, 53U, n_ref1, 15U, 33U);
    return;
}
void smavlink_unpack_set_global_position_setpoint_int(struct set_global_position_setpoint_int_msg* n_var0,
                                                      const uint8_t** n_var1)
{
    int32_t n_r0 = smavlink_unpack_int32_t(n_var1, 0U);
    
    *&n_var0->latitude = n_r0;
    
    int32_t n_r1 = smavlink_unpack_int32_t(n_var1, 4U);
    
    *&n_var0->longitude = n_r1;
    
    int32_t n_r2 = smavlink_unpack_int32_t(n_var1, 8U);
    
    *&n_var0->altitude = n_r2;
    
    int16_t n_r3 = smavlink_unpack_int16_t(n_var1, 12U);
    
    *&n_var0->yaw = n_r3;
    
    uint8_t n_r4 = smavlink_unpack_uint8_t(n_var1, 14U);
    
    *&n_var0->coordinate_frame = n_r4;
}
