/* This file has been autogenerated by Ivory
 * Compiler version  5326f414a5a63af59269d31f823a2e142af0b2c9
 */
#include <out.h>
#include <smavlink/pack.h>
#include "smavlink_message_system_time.h"
void smavlink_send_system_time(struct system_time_msg* n_var0,
                               struct smavlink_out_channel* n_var1,
                               struct smavlink_system* n_var2)
{
    uint8_t n_local0[12U] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t(* n_ref1)[12U] = &n_local0;
    uint64_t n_deref2 = *&n_var0->time_unix_usec;
    
    smavlink_pack_uint64_t(n_ref1, 0U, n_deref2);
    
    uint32_t n_deref3 = *&n_var0->time_boot_ms;
    
    smavlink_pack_uint32_t(n_ref1, 8U, n_deref3);
    smavlink_send_ivory(n_var1, n_var2, 2U, n_ref1, 12U, 137U);
    return;
}
