/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "smavlink_message_sys_status.h"
void smavlink_send_sys_status(struct sys_status_msg* n_var0,
                              struct smavlink_out_channel* n_var1,
                              struct smavlink_system* n_var2)
{
    uint8_t n_local0[31U] = {0};
    uint8_t* n_ref1 = n_local0;
    uint32_t n_deref2 = *&n_var0->onboard_control_sensors_present;
    
    smavlink_pack_uint32_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint32_t n_deref3 = *&n_var0->onboard_control_sensors_enabled;
    
    smavlink_pack_uint32_t((uint8_t*) n_ref1, 4U, n_deref3);
    
    uint32_t n_deref4 = *&n_var0->onboard_control_sensors_health;
    
    smavlink_pack_uint32_t((uint8_t*) n_ref1, 8U, n_deref4);
    
    uint16_t n_deref5 = *&n_var0->load;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 12U, n_deref5);
    
    uint16_t n_deref6 = *&n_var0->voltage_battery;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 14U, n_deref6);
    
    int16_t n_deref7 = *&n_var0->current_battery;
    
    smavlink_pack_int16_t((uint8_t*) n_ref1, 16U, n_deref7);
    
    uint16_t n_deref8 = *&n_var0->drop_rate_comm;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 18U, n_deref8);
    
    uint16_t n_deref9 = *&n_var0->errors_comm;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 20U, n_deref9);
    
    uint16_t n_deref10 = *&n_var0->errors_count1;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 22U, n_deref10);
    
    uint16_t n_deref11 = *&n_var0->errors_count2;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 24U, n_deref11);
    
    uint16_t n_deref12 = *&n_var0->errors_count3;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 26U, n_deref12);
    
    uint16_t n_deref13 = *&n_var0->errors_count4;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 28U, n_deref13);
    
    int8_t n_deref14 = *&n_var0->battery_remaining;
    
    smavlink_pack_int8_t((uint8_t*) n_ref1, 30U, n_deref14);
    smavlink_send_ivory(n_var1, n_var2, 1U, (uint8_t*) n_ref1, 31U, 124U);
    return;
}
void smavlink_unpack_sys_status(struct sys_status_msg* n_var0, const
                                uint8_t* n_var1)
{
    uint32_t n_r0 = smavlink_unpack_uint32_t(n_var1, 0U);
    
    *&n_var0->onboard_control_sensors_present = n_r0;
    
    uint32_t n_r1 = smavlink_unpack_uint32_t(n_var1, 4U);
    
    *&n_var0->onboard_control_sensors_enabled = n_r1;
    
    uint32_t n_r2 = smavlink_unpack_uint32_t(n_var1, 8U);
    
    *&n_var0->onboard_control_sensors_health = n_r2;
    
    uint16_t n_r3 = smavlink_unpack_uint16_t(n_var1, 12U);
    
    *&n_var0->load = n_r3;
    
    uint16_t n_r4 = smavlink_unpack_uint16_t(n_var1, 14U);
    
    *&n_var0->voltage_battery = n_r4;
    
    int16_t n_r5 = smavlink_unpack_int16_t(n_var1, 16U);
    
    *&n_var0->current_battery = n_r5;
    
    uint16_t n_r6 = smavlink_unpack_uint16_t(n_var1, 18U);
    
    *&n_var0->drop_rate_comm = n_r6;
    
    uint16_t n_r7 = smavlink_unpack_uint16_t(n_var1, 20U);
    
    *&n_var0->errors_comm = n_r7;
    
    uint16_t n_r8 = smavlink_unpack_uint16_t(n_var1, 22U);
    
    *&n_var0->errors_count1 = n_r8;
    
    uint16_t n_r9 = smavlink_unpack_uint16_t(n_var1, 24U);
    
    *&n_var0->errors_count2 = n_r9;
    
    uint16_t n_r10 = smavlink_unpack_uint16_t(n_var1, 26U);
    
    *&n_var0->errors_count3 = n_r10;
    
    uint16_t n_r11 = smavlink_unpack_uint16_t(n_var1, 28U);
    
    *&n_var0->errors_count4 = n_r11;
    
    int8_t n_r12 = smavlink_unpack_int8_t(n_var1, 30U);
    
    *&n_var0->battery_remaining = n_r12;
}
