/* This file has been autogenerated by Ivory
 * Compiler version  Version {versionBranch = [0,1,0,0], versionTags = []}
 */
#include <smavlink/pack.h>
#include "smavlink_message_vfr_hud.h"
void smavlink_send_vfr_hud(struct vfr_hud_msg* n_var0,
                           struct smavlink_out_channel* n_var1,
                           struct smavlink_system* n_var2)
{
    uint8_t n_local0[20U] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                             0, 0, 0};
    uint8_t* n_ref1 = n_local0;
    float n_deref2 = *&n_var0->airspeed;
    
    smavlink_pack_float((uint8_t*) n_ref1, 0U, n_deref2);
    
    float n_deref3 = *&n_var0->groundspeed;
    
    smavlink_pack_float((uint8_t*) n_ref1, 4U, n_deref3);
    
    float n_deref4 = *&n_var0->alt;
    
    smavlink_pack_float((uint8_t*) n_ref1, 8U, n_deref4);
    
    float n_deref5 = *&n_var0->climb;
    
    smavlink_pack_float((uint8_t*) n_ref1, 12U, n_deref5);
    
    int16_t n_deref6 = *&n_var0->heading;
    
    smavlink_pack_int16_t((uint8_t*) n_ref1, 16U, n_deref6);
    
    uint16_t n_deref7 = *&n_var0->throttle;
    
    smavlink_pack_uint16_t((uint8_t*) n_ref1, 18U, n_deref7);
    smavlink_send_ivory(n_var1, n_var2, 74U, (uint8_t*) n_ref1, 20U, 20U);
    return;
}
void smavlink_unpack_vfr_hud(struct vfr_hud_msg* n_var0, const uint8_t** n_var1)
{
    float n_r0 = smavlink_unpack_float(n_var1, 0U);
    
    *&n_var0->airspeed = n_r0;
    
    float n_r1 = smavlink_unpack_float(n_var1, 4U);
    
    *&n_var0->groundspeed = n_r1;
    
    float n_r2 = smavlink_unpack_float(n_var1, 8U);
    
    *&n_var0->alt = n_r2;
    
    float n_r3 = smavlink_unpack_float(n_var1, 12U);
    
    *&n_var0->climb = n_r3;
    
    int16_t n_r4 = smavlink_unpack_int16_t(n_var1, 16U);
    
    *&n_var0->heading = n_r4;
    
    uint16_t n_r5 = smavlink_unpack_uint16_t(n_var1, 18U);
    
    *&n_var0->throttle = n_r5;
}
