/* This file has been autogenerated by Ivory
 * Compiler version  Version {versionBranch = [0,1,0,0], versionTags = []}
 */
#include <smavlink/pack.h>
#include "smavlink_message_heartbeat.h"
void smavlink_send_heartbeat(struct heartbeat_msg* n_var0,
                             struct smavlink_out_channel* n_var1,
                             struct smavlink_system* n_var2)
{
    uint8_t n_local0[9U] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t(* n_ref1)[9U] = &n_local0;
    uint32_t n_deref2 = *&n_var0->custom_mode;
    
    smavlink_pack_uint32_t(n_ref1, 0U, n_deref2);
    
    uint8_t n_deref3 = *&n_var0->mavtype;
    
    smavlink_pack_uint8_t(n_ref1, 4U, n_deref3);
    
    uint8_t n_deref4 = *&n_var0->autopilot;
    
    smavlink_pack_uint8_t(n_ref1, 5U, n_deref4);
    
    uint8_t n_deref5 = *&n_var0->base_mode;
    
    smavlink_pack_uint8_t(n_ref1, 6U, n_deref5);
    
    uint8_t n_deref6 = *&n_var0->system_status;
    
    smavlink_pack_uint8_t(n_ref1, 7U, n_deref6);
    
    uint8_t n_deref7 = *&n_var0->mavlink_version;
    
    smavlink_pack_uint8_t(n_ref1, 8U, n_deref7);
    smavlink_send_ivory(n_var1, n_var2, 0U, n_ref1, 9U, 50U);
    return;
}
void smavlink_unpack_heartbeat(struct heartbeat_msg* n_var0, const
                               uint8_t** n_var1)
{
    uint32_t n_r0 = smavlink_unpack_uint32_t(n_var1, 0U);
    
    *&n_var0->custom_mode = n_r0;
    
    uint8_t n_r1 = smavlink_unpack_uint8_t(n_var1, 4U);
    
    *&n_var0->mavtype = n_r1;
    
    uint8_t n_r2 = smavlink_unpack_uint8_t(n_var1, 5U);
    
    *&n_var0->autopilot = n_r2;
    
    uint8_t n_r3 = smavlink_unpack_uint8_t(n_var1, 6U);
    
    *&n_var0->base_mode = n_r3;
    
    uint8_t n_r4 = smavlink_unpack_uint8_t(n_var1, 7U);
    
    *&n_var0->system_status = n_r4;
    
    uint8_t n_r5 = smavlink_unpack_uint8_t(n_var1, 8U);
    
    *&n_var0->mavlink_version = n_r5;
}
