
############################################################################
#
#   File: /home/camkes/june-drop-odroid-manifest/apps/can_proxy_odroid_test/./make_template/Makefile
#   Created on: 2015/06/27 19:04:09
#   using Dulcimer AADL system build tool suite 
#
#   ***AUTOGENERATED CODE (modify if you need to :-) ***
#
# TODO: add DARPA license?
#
# This file is an automatically generated makefile from the AADL build 
# system designed for the CAmkES build system.  It will work for projects 
# in which all C files and libraries are "known" to the AADL file.  
# However, for projects with more complex dependencies and "external" 
# components that are not described in the AADL file, it will need to be 
# extended.
#
############################################################################
TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := sys_impl_assembly.camkes

# For time server: subdirectory containing extra templates.
TEMPLATES := ../../projects/templates ../../projects/global-components/templates


include TimeServerOdroid/TimeServer.mk
include ${PWD}/apps/can_proxy_odroid_test/make_template/Makefile

###### CAN files below

gpio_LIBS += platsupport
spi_LIBS += platsupport
clk_LIBS += platsupport

can_HFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/can/include/*.h)) \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/include/*.h))
can_CFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/can/src/*.c))

spi_HFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/spi/include/*.h)) \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/include/*.h))
spi_CFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/spi/src/*.c))

clk_HFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/include/*.h)) \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/clk/include/*.h))
clk_CFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/clk/src/*.c))

gpio_HFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/include/*.h)) \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/gpio/include/*.h))
gpio_CFILES := \
    $(patsubst ${SOURCE_DIR}/%,%,$(wildcard ${SOURCE_DIR}/components/gpio/src/*.c))

###### End CAN files


include ${PWD}/tools/camkes/camkes.mk

###################################################################
