{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.CommandLong where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

commandLongMsgId :: Word8
commandLongMsgId = 76

commandLongCrcExtra :: Word8
commandLongCrcExtra = 152

data CommandLongMsg =
  CommandLongMsg
    { param1 :: Float
    , param2 :: Float
    , param3 :: Float
    , param4 :: Float
    , param5 :: Float
    , param6 :: Float
    , param7 :: Float
    , command :: Word16
    , target_system :: Word8
    , target_component :: Word8
    , confirmation :: Word8
    }

getCommandLongMsg :: Get CommandLongMsg
getCommandLongMsg = do
  param1 <- get
  param2 <- get
  param3 <- get
  param4 <- get
  param5 <- get
  param6 <- get
  param7 <- get
  command <- get
  target_system <- get
  target_component <- get
  confirmation <- get
  return CommandLongMsg{..}

putCommandLongMsg :: CommandLongMsg -> Put
putCommandLongMsg CommandLongMsg{..} = do
  put param1
  put param2
  put param3
  put param4
  put param5
  put param6
  put param7
  put command
  put target_system
  put target_component
  put confirmation

