{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.DebugVect where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

debugVectMsgId :: Word8
debugVectMsgId = 250

debugVectCrcExtra :: Word8
debugVectCrcExtra = 49

data DebugVectMsg =
  DebugVectMsg
    { time_usec :: Word64
    , x :: Float
    , y :: Float
    , z :: Float
    , name :: Vector 10 Word8
    }

getDebugVectMsg :: Get DebugVectMsg
getDebugVectMsg = do
  time_usec <- get
  x <- get
  y <- get
  z <- get
  name <- get
  return DebugVectMsg{..}

putDebugVectMsg :: DebugVectMsg -> Put
putDebugVectMsg DebugVectMsg{..} = do
  put time_usec
  put x
  put y
  put z
  put name

