{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.LocalPositionNed where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

localPositionNedMsgId :: Word8
localPositionNedMsgId = 32

localPositionNedCrcExtra :: Word8
localPositionNedCrcExtra = 185

data LocalPositionNedMsg =
  LocalPositionNedMsg
    { time_boot_ms :: Word32
    , x :: Float
    , y :: Float
    , z :: Float
    , vx :: Float
    , vy :: Float
    , vz :: Float
    }

getLocalPositionNedMsg :: Get LocalPositionNedMsg
getLocalPositionNedMsg = do
  time_boot_ms <- get
  x <- get
  y <- get
  z <- get
  vx <- get
  vy <- get
  vz <- get
  return LocalPositionNedMsg{..}

putLocalPositionNedMsg :: LocalPositionNedMsg -> Put
putLocalPositionNedMsg LocalPositionNedMsg{..} = do
  put time_boot_ms
  put x
  put y
  put z
  put vx
  put vy
  put vz

