{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.ManualControl where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

manualControlMsgId :: Word8
manualControlMsgId = 69

manualControlCrcExtra :: Word8
manualControlCrcExtra = 243

data ManualControlMsg =
  ManualControlMsg
    { x :: Int16
    , y :: Int16
    , z :: Int16
    , r :: Int16
    , buttons :: Word16
    , target :: Word8
    }

getManualControlMsg :: Get ManualControlMsg
getManualControlMsg = do
  x <- get
  y <- get
  z <- get
  r <- get
  buttons <- get
  target <- get
  return ManualControlMsg{..}

putManualControlMsg :: ManualControlMsg -> Put
putManualControlMsg ManualControlMsg{..} = do
  put x
  put y
  put z
  put r
  put buttons
  put target

