{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.ManualSetpoint where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

manualSetpointMsgId :: Word8
manualSetpointMsgId = 81

manualSetpointCrcExtra :: Word8
manualSetpointCrcExtra = 106

data ManualSetpointMsg =
  ManualSetpointMsg
    { time_boot_ms :: Word32
    , roll :: Float
    , pitch :: Float
    , yaw :: Float
    , thrust :: Float
    , mode_switch :: Word8
    , manual_override_switch :: Word8
    }

getManualSetpointMsg :: Get ManualSetpointMsg
getManualSetpointMsg = do
  time_boot_ms <- get
  roll <- get
  pitch <- get
  yaw <- get
  thrust <- get
  mode_switch <- get
  manual_override_switch <- get
  return ManualSetpointMsg{..}

putManualSetpointMsg :: ManualSetpointMsg -> Put
putManualSetpointMsg ManualSetpointMsg{..} = do
  put time_boot_ms
  put roll
  put pitch
  put yaw
  put thrust
  put mode_switch
  put manual_override_switch

