{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.MissionRequest where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

missionRequestMsgId :: Word8
missionRequestMsgId = 40

missionRequestCrcExtra :: Word8
missionRequestCrcExtra = 230

data MissionRequestMsg =
  MissionRequestMsg
    { mission_request_seq :: Word16
    , target_system :: Word8
    , target_component :: Word8
    }

getMissionRequestMsg :: Get MissionRequestMsg
getMissionRequestMsg = do
  mission_request_seq <- get
  target_system <- get
  target_component <- get
  return MissionRequestMsg{..}

putMissionRequestMsg :: MissionRequestMsg -> Put
putMissionRequestMsg MissionRequestMsg{..} = do
  put mission_request_seq
  put target_system
  put target_component

