{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.NamedValueInt where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

namedValueIntMsgId :: Word8
namedValueIntMsgId = 252

namedValueIntCrcExtra :: Word8
namedValueIntCrcExtra = 44

data NamedValueIntMsg =
  NamedValueIntMsg
    { time_boot_ms :: Word32
    , value :: Int16
    , name :: Vector 10 Word8
    }

getNamedValueIntMsg :: Get NamedValueIntMsg
getNamedValueIntMsg = do
  time_boot_ms <- get
  value <- get
  name <- get
  return NamedValueIntMsg{..}

putNamedValueIntMsg :: NamedValueIntMsg -> Put
putNamedValueIntMsg NamedValueIntMsg{..} = do
  put time_boot_ms
  put value
  put name

