{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.ParamRequestList where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

paramRequestListMsgId :: Word8
paramRequestListMsgId = 21

paramRequestListCrcExtra :: Word8
paramRequestListCrcExtra = 159

data ParamRequestListMsg =
  ParamRequestListMsg
    { target_system :: Word8
    , target_component :: Word8
    }

getParamRequestListMsg :: Get ParamRequestListMsg
getParamRequestListMsg = do
  target_system <- get
  target_component <- get
  return ParamRequestListMsg{..}

putParamRequestListMsg :: ParamRequestListMsg -> Put
putParamRequestListMsg ParamRequestListMsg{..} = do
  put target_system
  put target_component

