{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.ParamRequestRead where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

paramRequestReadMsgId :: Word8
paramRequestReadMsgId = 20

paramRequestReadCrcExtra :: Word8
paramRequestReadCrcExtra = 214

data ParamRequestReadMsg =
  ParamRequestReadMsg
    { param_index :: Int16
    , target_system :: Word8
    , target_component :: Word8
    , param_id :: Vector 16 Word8
    }

getParamRequestReadMsg :: Get ParamRequestReadMsg
getParamRequestReadMsg = do
  param_index <- get
  target_system <- get
  target_component <- get
  param_id <- get
  return ParamRequestReadMsg{..}

putParamRequestReadMsg :: ParamRequestReadMsg -> Put
putParamRequestReadMsg ParamRequestReadMsg{..} = do
  put param_index
  put target_system
  put target_component
  put param_id

