{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.Ping where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

pingMsgId :: Word8
pingMsgId = 4

pingCrcExtra :: Word8
pingCrcExtra = 237

data PingMsg =
  PingMsg
    { time_usec :: Word64
    , ping_seq :: Word32
    , target_system :: Word8
    , target_component :: Word8
    }

getPingMsg :: Get PingMsg
getPingMsg = do
  time_usec <- get
  ping_seq <- get
  target_system <- get
  target_component <- get
  return PingMsg{..}

putPingMsg :: PingMsg -> Put
putPingMsg PingMsg{..} = do
  put time_usec
  put ping_seq
  put target_system
  put target_component

