{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.RcChannelsOverride where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

rcChannelsOverrideMsgId :: Word8
rcChannelsOverrideMsgId = 70

rcChannelsOverrideCrcExtra :: Word8
rcChannelsOverrideCrcExtra = 124

data RcChannelsOverrideMsg =
  RcChannelsOverrideMsg
    { chan1_raw :: Word16
    , chan2_raw :: Word16
    , chan3_raw :: Word16
    , chan4_raw :: Word16
    , chan5_raw :: Word16
    , chan6_raw :: Word16
    , chan7_raw :: Word16
    , chan8_raw :: Word16
    , target_system :: Word8
    , target_component :: Word8
    }

getRcChannelsOverrideMsg :: Get RcChannelsOverrideMsg
getRcChannelsOverrideMsg = do
  chan1_raw <- get
  chan2_raw <- get
  chan3_raw <- get
  chan4_raw <- get
  chan5_raw <- get
  chan6_raw <- get
  chan7_raw <- get
  chan8_raw <- get
  target_system <- get
  target_component <- get
  return RcChannelsOverrideMsg{..}

putRcChannelsOverrideMsg :: RcChannelsOverrideMsg -> Put
putRcChannelsOverrideMsg RcChannelsOverrideMsg{..} = do
  put chan1_raw
  put chan2_raw
  put chan3_raw
  put chan4_raw
  put chan5_raw
  put chan6_raw
  put chan7_raw
  put chan8_raw
  put target_system
  put target_component

