{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.SafetySetAllowedArea where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

safetySetAllowedAreaMsgId :: Word8
safetySetAllowedAreaMsgId = 54

safetySetAllowedAreaCrcExtra :: Word8
safetySetAllowedAreaCrcExtra = 15

data SafetySetAllowedAreaMsg =
  SafetySetAllowedAreaMsg
    { p1x :: Float
    , p1y :: Float
    , p1z :: Float
    , p2x :: Float
    , p2y :: Float
    , p2z :: Float
    , target_system :: Word8
    , target_component :: Word8
    , frame :: Word8
    }

getSafetySetAllowedAreaMsg :: Get SafetySetAllowedAreaMsg
getSafetySetAllowedAreaMsg = do
  p1x <- get
  p1y <- get
  p1z <- get
  p2x <- get
  p2y <- get
  p2z <- get
  target_system <- get
  target_component <- get
  frame <- get
  return SafetySetAllowedAreaMsg{..}

putSafetySetAllowedAreaMsg :: SafetySetAllowedAreaMsg -> Put
putSafetySetAllowedAreaMsg SafetySetAllowedAreaMsg{..} = do
  put p1x
  put p1y
  put p1z
  put p2x
  put p2y
  put p2z
  put target_system
  put target_component
  put frame

