{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.ScaledPressure where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

scaledPressureMsgId :: Word8
scaledPressureMsgId = 29

scaledPressureCrcExtra :: Word8
scaledPressureCrcExtra = 115

data ScaledPressureMsg =
  ScaledPressureMsg
    { time_boot_ms :: Word32
    , press_abs :: Float
    , press_diff :: Float
    , temperature :: Int16
    }

getScaledPressureMsg :: Get ScaledPressureMsg
getScaledPressureMsg = do
  time_boot_ms <- get
  press_abs <- get
  press_diff <- get
  temperature <- get
  return ScaledPressureMsg{..}

putScaledPressureMsg :: ScaledPressureMsg -> Put
putScaledPressureMsg ScaledPressureMsg{..} = do
  put time_boot_ms
  put press_abs
  put press_diff
  put temperature

