{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.Setpoint6dof where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

setpoint6dofMsgId :: Word8
setpoint6dofMsgId = 149

setpoint6dofCrcExtra :: Word8
setpoint6dofCrcExtra = 15

data Setpoint6dofMsg =
  Setpoint6dofMsg
    { trans_x :: Float
    , trans_y :: Float
    , trans_z :: Float
    , rot_x :: Float
    , rot_y :: Float
    , rot_z :: Float
    , target_system :: Word8
    }

getSetpoint6dofMsg :: Get Setpoint6dofMsg
getSetpoint6dofMsg = do
  trans_x <- get
  trans_y <- get
  trans_z <- get
  rot_x <- get
  rot_y <- get
  rot_z <- get
  target_system <- get
  return Setpoint6dofMsg{..}

putSetpoint6dofMsg :: Setpoint6dofMsg -> Put
putSetpoint6dofMsg Setpoint6dofMsg{..} = do
  put trans_x
  put trans_y
  put trans_z
  put rot_x
  put rot_y
  put rot_z
  put target_system

