{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.VfrHud where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

vfrHudMsgId :: Word8
vfrHudMsgId = 74

vfrHudCrcExtra :: Word8
vfrHudCrcExtra = 20

data VfrHudMsg =
  VfrHudMsg
    { airspeed :: Float
    , groundspeed :: Float
    , alt :: Float
    , climb :: Float
    , heading :: Int16
    , throttle :: Word16
    }

getVfrHudMsg :: Get VfrHudMsg
getVfrHudMsg = do
  airspeed <- get
  groundspeed <- get
  alt <- get
  climb <- get
  heading <- get
  throttle <- get
  return VfrHudMsg{..}

putVfrHudMsg :: VfrHudMsg -> Put
putVfrHudMsg VfrHudMsg{..} = do
  put airspeed
  put groundspeed
  put alt
  put climb
  put heading
  put throttle

