{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_haskell.py

module SMACCMPilot.Mavlink.Native.Messages.VisionSpeedEstimate where

import Data.Word
import Data.Int
import Data.Sized.Matrix (Vector)
import Data.Serialize
import SMACCMPilot.Mavlink.Native.Serialize

visionSpeedEstimateMsgId :: Word8
visionSpeedEstimateMsgId = 103

visionSpeedEstimateCrcExtra :: Word8
visionSpeedEstimateCrcExtra = 208

data VisionSpeedEstimateMsg =
  VisionSpeedEstimateMsg
    { usec :: Word64
    , x :: Float
    , y :: Float
    , z :: Float
    }

getVisionSpeedEstimateMsg :: Get VisionSpeedEstimateMsg
getVisionSpeedEstimateMsg = do
  usec <- get
  x <- get
  y <- get
  z <- get
  return VisionSpeedEstimateMsg{..}

putVisionSpeedEstimateMsg :: VisionSpeedEstimateMsg -> Put
putVisionSpeedEstimateMsg VisionSpeedEstimateMsg{..} = do
  put usec
  put x
  put y
  put z

