/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "param.h"
struct param_info* param_new()
{
    uint16_t* n_ref0 = &g_param_count;
    uint16_t n_deref1 = *n_ref0;
    
    *n_ref0 = (n_deref1 + 1U) % 512U;
    
    struct param_info* n_ref2 = g_param_info;
    struct param_info* n_let3 = &n_ref2[n_deref1];
    
    *&n_let3->param_index = n_deref1;
    *&n_let3->param_requested = 0U;
    return n_let3;
}
void param_init_u8(char* n_var0, uint8_t* n_var1)
{
    struct param_info* n_r0 = param_new();
    
    ivory_strlcpy((char*) n_r0->param_name, n_var0, 32U);
    *&n_r0->param_type = 0U;
    *&n_r0->param_ptr_u8 = n_var1;
}
void param_init_u16(char* n_var0, uint16_t* n_var1)
{
    struct param_info* n_r0 = param_new();
    
    ivory_strlcpy((char*) n_r0->param_name, n_var0, 32U);
    *&n_r0->param_type = 1U;
    *&n_r0->param_ptr_u16 = n_var1;
}
void param_init_u32(char* n_var0, uint32_t* n_var1)
{
    struct param_info* n_r0 = param_new();
    
    ivory_strlcpy((char*) n_r0->param_name, n_var0, 32U);
    *&n_r0->param_type = 2U;
    *&n_r0->param_ptr_u32 = n_var1;
}
void param_init_float(char* n_var0, float* n_var1)
{
    struct param_info* n_r0 = param_new();
    
    ivory_strlcpy((char*) n_r0->param_name, n_var0, 32U);
    *&n_r0->param_type = 3U;
    *&n_r0->param_ptr_float = n_var1;
}
struct param_info* param_get_by_name(const char* n_var0)
{
    uint16_t* n_ref0 = &g_param_count;
    uint16_t n_deref1 = *n_ref0;
    
    if (n_deref1 == 0U) {
        return NULL;
    } else { }
    
    struct param_info* n_ref2 = g_param_info;
    
    for (uint16_t n_ix3 = 0U; n_ix3 <= (n_deref1 - 1U) % 512U; n_ix3 = n_ix3 +
         1U) {
        struct param_info* n_let4 = &n_ref2[n_ix3];
        const char* n_let5 = (const char*) n_let4->param_name;
        uint32_t n_let6 = 32U;
        int32_t n_r7 = strncmp(n_var0, n_let5, n_let6);
        
        if (n_r7 == 0) {
            return n_let4;
        } else { }
    }
    return NULL;
}
struct param_info* param_get_by_index(uint16_t n_var0)
{
    uint16_t* n_ref0 = &g_param_count;
    uint16_t n_deref1 = *n_ref0;
    
    if (n_var0 >= n_deref1) {
        return NULL;
    } else { }
    
    struct param_info* n_ref2 = g_param_info;
    
    return &n_ref2[n_var0];
}
struct param_info* param_get_requested()
{
    uint16_t* n_ref0 = &g_param_count;
    uint16_t n_deref1 = *n_ref0;
    
    if (n_deref1 == 0U) {
        return NULL;
    } else { }
    
    struct param_info* n_ref2 = g_param_info;
    
    for (uint16_t n_ix3 = 0U; n_ix3 <= (n_deref1 - 1U) % 512U; n_ix3 = n_ix3 +
         1U) {
        struct param_info* n_let4 = &n_ref2[n_ix3];
        uint8_t n_deref5 = *&n_let4->param_requested;
        
        if (n_deref5 != 0U) {
            return n_let4;
        } else { }
    }
    return NULL;
}
float param_get_float_value(struct param_info* n_var0)
{
    uint8_t n_deref0 = *&n_var0->param_type;
    
    if (n_deref0 == 0U) {
        uint8_t* n_deref1 = *&n_var0->param_ptr_u8;
        
        if (NULL != n_deref1) {
            uint8_t n_deref2 = *n_deref1;
            
            return (float) n_deref2;
        } else {
            return 0.0f;
        }
    } else { }
    if (n_deref0 == 1U) {
        uint16_t* n_deref3 = *&n_var0->param_ptr_u16;
        
        if (NULL != n_deref3) {
            uint16_t n_deref4 = *n_deref3;
            
            return (float) n_deref4;
        } else {
            return 0.0f;
        }
    } else { }
    if (n_deref0 == 2U) {
        uint32_t* n_deref5 = *&n_var0->param_ptr_u32;
        
        if (NULL != n_deref5) {
            uint32_t n_deref6 = *n_deref5;
            
            return (float) n_deref6;
        } else {
            return 0.0f;
        }
    } else { }
    if (n_deref0 == 3U) {
        float* n_deref7 = *&n_var0->param_ptr_float;
        
        if (NULL != n_deref7) {
            float n_deref8 = *n_deref7;
            
            return n_deref8;
        } else {
            return 0.0f;
        }
    } else { }
    return 0.0f;
}
struct param_info g_param_info[512U];
uint16_t g_param_count;
