#
# Makefile
#
# Copyright (C) 2012, Galois, Inc.
# All Rights Reserved.
#
# This software is released under the "BSD3" license.  Read the file
# "LICENSE" for more information.
#

topdir := ../..

include $(topdir)/mk/cmd.lib

all:
	$(MAKE) -C $(topdir) libhwf4.a
