{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.Attitude where

import SMACCMPilot.Mavlink.Pack
import SMACCMPilot.Mavlink.Unpack
import SMACCMPilot.Mavlink.Send
import qualified SMACCMPilot.Communications as Comm

import Ivory.Language
import Ivory.Stdlib

attitudeMsgId :: Uint8
attitudeMsgId = 30

attitudeCrcExtra :: Uint8
attitudeCrcExtra = 39

attitudeModule :: Module
attitudeModule = package "mavlink_attitude_msg" $ do
  depend packModule
  depend mavlinkSendModule
  incl mkAttitudeSender
  incl attitudeUnpack
  defStruct (Proxy :: Proxy "attitude_msg")

[ivory|
struct attitude_msg
  { time_boot_ms :: Stored Uint32
  ; roll :: Stored IFloat
  ; pitch :: Stored IFloat
  ; yaw :: Stored IFloat
  ; rollspeed :: Stored IFloat
  ; pitchspeed :: Stored IFloat
  ; yawspeed :: Stored IFloat
  }
|]

mkAttitudeSender ::
  Def ('[ ConstRef s0 (Struct "attitude_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 Comm.MAVLinkArray -- tx buffer
        ] :-> ())
mkAttitudeSender =
  proc "mavlink_attitude_msg_send"
  $ \msg seqNum sendArr -> body
  $ do
  arr <- local (iarray [] :: Init (Array 28 (Stored Uint8)))
  let buf = toCArray arr
  call_ pack buf 0 =<< deref (msg ~> time_boot_ms)
  call_ pack buf 4 =<< deref (msg ~> roll)
  call_ pack buf 8 =<< deref (msg ~> pitch)
  call_ pack buf 12 =<< deref (msg ~> yaw)
  call_ pack buf 16 =<< deref (msg ~> rollspeed)
  call_ pack buf 20 =<< deref (msg ~> pitchspeed)
  call_ pack buf 24 =<< deref (msg ~> yawspeed)
  -- 6: header len, 2: CRC len
  let usedLen = 6 + 28 + 2 :: Integer
  let sendArrLen = arrayLen sendArr
  if sendArrLen < usedLen
    then error "attitude payload of length 28 is too large!"
    else do -- Copy, leaving room for the payload
            arrCopy sendArr arr 6
            call_ mavlinkSendWithWriter
                    attitudeMsgId
                    attitudeCrcExtra
                    28
                    seqNum
                    sendArr
            let usedLenIx = fromInteger usedLen
            -- Zero out the unused portion of the array.
            for (fromInteger sendArrLen - usedLenIx) $ \ix ->
              store (sendArr ! (ix + usedLenIx)) 0
            retVoid

instance MavlinkUnpackableMsg "attitude_msg" where
    unpackMsg = ( attitudeUnpack , attitudeMsgId )

attitudeUnpack :: Def ('[ Ref s1 (Struct "attitude_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
attitudeUnpack = proc "mavlink_attitude_unpack" $ \ msg buf -> body $ do
  store (msg ~> time_boot_ms) =<< call unpack buf 0
  store (msg ~> roll) =<< call unpack buf 4
  store (msg ~> pitch) =<< call unpack buf 8
  store (msg ~> yaw) =<< call unpack buf 12
  store (msg ~> rollspeed) =<< call unpack buf 16
  store (msg ~> pitchspeed) =<< call unpack buf 20
  store (msg ~> yawspeed) =<< call unpack buf 24

