{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.ChangeOperatorControlAck where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Send
import SMACCMPilot.Mavlink.Unpack

changeOperatorControlAckMsgId :: Uint8
changeOperatorControlAckMsgId = 6

changeOperatorControlAckCrcExtra :: Uint8
changeOperatorControlAckCrcExtra = 104

changeOperatorControlAckModule :: Module
changeOperatorControlAckModule = package "mavlink_change_operator_control_ack_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkChangeOperatorControlAckSender
  incl changeOperatorControlAckUnpack
  defStruct (Proxy :: Proxy "change_operator_control_ack_msg")
  incl changeOperatorControlAckPackRef
  incl changeOperatorControlAckUnpackRef

[ivory|
struct change_operator_control_ack_msg
  { gcs_system_id :: Stored Uint8
  ; control_request :: Stored Uint8
  ; ack :: Stored Uint8
  }
|]

mkChangeOperatorControlAckSender ::
  Def ('[ ConstRef s0 (Struct "change_operator_control_ack_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkChangeOperatorControlAckSender = makeMavlinkSender "change_operator_control_ack_msg" changeOperatorControlAckMsgId changeOperatorControlAckCrcExtra

instance MavlinkUnpackableMsg "change_operator_control_ack_msg" where
    unpackMsg = ( changeOperatorControlAckUnpack , changeOperatorControlAckMsgId )

changeOperatorControlAckUnpack :: Def ('[ Ref s1 (Struct "change_operator_control_ack_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
changeOperatorControlAckUnpack = proc "mavlink_change_operator_control_ack_unpack" $ \ msg buf -> body $ unpackRef buf 0 msg

changeOperatorControlAckPackRef :: Def ('[ Ref s1 (CArray (Stored Uint8))
                              , Uint32
                              , ConstRef s2 (Struct "change_operator_control_ack_msg")
                              ] :-> () )
changeOperatorControlAckPackRef = proc "mavlink_change_operator_control_ack_pack_ref" $ \ buf off msg -> body $ do
  packRef buf (off + 0) (msg ~> gcs_system_id)
  packRef buf (off + 1) (msg ~> control_request)
  packRef buf (off + 2) (msg ~> ack)

changeOperatorControlAckUnpackRef :: Def ('[ ConstRef s1 (CArray (Stored Uint8))
                                , Uint32
                                , Ref s2 (Struct "change_operator_control_ack_msg")
                                ] :-> () )
changeOperatorControlAckUnpackRef = proc "mavlink_change_operator_control_ack_unpack_ref" $ \ buf off msg -> body $ do
  unpackRef buf (off + 0) (msg ~> gcs_system_id)
  unpackRef buf (off + 1) (msg ~> control_request)
  unpackRef buf (off + 2) (msg ~> ack)

instance SerializableRef (Struct "change_operator_control_ack_msg") where
  packRef = call_ changeOperatorControlAckPackRef
  unpackRef = call_ changeOperatorControlAckUnpackRef
