{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.GlobalPositionInt where

import SMACCMPilot.Mavlink.Pack
import SMACCMPilot.Mavlink.Unpack
import SMACCMPilot.Mavlink.Send
import qualified SMACCMPilot.Communications as Comm

import Ivory.Language
import Ivory.Stdlib

globalPositionIntMsgId :: Uint8
globalPositionIntMsgId = 33

globalPositionIntCrcExtra :: Uint8
globalPositionIntCrcExtra = 104

globalPositionIntModule :: Module
globalPositionIntModule = package "mavlink_global_position_int_msg" $ do
  depend packModule
  depend mavlinkSendModule
  incl mkGlobalPositionIntSender
  incl globalPositionIntUnpack
  defStruct (Proxy :: Proxy "global_position_int_msg")

[ivory|
struct global_position_int_msg
  { time_boot_ms :: Stored Uint32
  ; lat :: Stored Sint32
  ; lon :: Stored Sint32
  ; alt :: Stored Sint32
  ; relative_alt :: Stored Sint32
  ; vx :: Stored Sint16
  ; vy :: Stored Sint16
  ; vz :: Stored Sint16
  ; hdg :: Stored Uint16
  }
|]

mkGlobalPositionIntSender ::
  Def ('[ ConstRef s0 (Struct "global_position_int_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 Comm.MAVLinkArray -- tx buffer
        ] :-> ())
mkGlobalPositionIntSender =
  proc "mavlink_global_position_int_msg_send"
  $ \msg seqNum sendArr -> body
  $ do
  arr <- local (iarray [] :: Init (Array 28 (Stored Uint8)))
  let buf = toCArray arr
  call_ pack buf 0 =<< deref (msg ~> time_boot_ms)
  call_ pack buf 4 =<< deref (msg ~> lat)
  call_ pack buf 8 =<< deref (msg ~> lon)
  call_ pack buf 12 =<< deref (msg ~> alt)
  call_ pack buf 16 =<< deref (msg ~> relative_alt)
  call_ pack buf 20 =<< deref (msg ~> vx)
  call_ pack buf 22 =<< deref (msg ~> vy)
  call_ pack buf 24 =<< deref (msg ~> vz)
  call_ pack buf 26 =<< deref (msg ~> hdg)
  -- 6: header len, 2: CRC len
  let usedLen = 6 + 28 + 2 :: Integer
  let sendArrLen = arrayLen sendArr
  if sendArrLen < usedLen
    then error "globalPositionInt payload of length 28 is too large!"
    else do -- Copy, leaving room for the payload
            arrCopy sendArr arr 6
            call_ mavlinkSendWithWriter
                    globalPositionIntMsgId
                    globalPositionIntCrcExtra
                    28
                    seqNum
                    sendArr

instance MavlinkUnpackableMsg "global_position_int_msg" where
    unpackMsg = ( globalPositionIntUnpack , globalPositionIntMsgId )

globalPositionIntUnpack :: Def ('[ Ref s1 (Struct "global_position_int_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
globalPositionIntUnpack = proc "mavlink_global_position_int_unpack" $ \ msg buf -> body $ do
  store (msg ~> time_boot_ms) =<< call unpack buf 0
  store (msg ~> lat) =<< call unpack buf 4
  store (msg ~> lon) =<< call unpack buf 8
  store (msg ~> alt) =<< call unpack buf 12
  store (msg ~> relative_alt) =<< call unpack buf 16
  store (msg ~> vx) =<< call unpack buf 20
  store (msg ~> vy) =<< call unpack buf 22
  store (msg ~> vz) =<< call unpack buf 24
  store (msg ~> hdg) =<< call unpack buf 26

