{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.GpsRawInt where

import Ivory.Serialize
import SMACCMPilot.Mavlink.Unpack
import SMACCMPilot.Mavlink.Send

import Ivory.Language
import Ivory.Stdlib

gpsRawIntMsgId :: Uint8
gpsRawIntMsgId = 24

gpsRawIntCrcExtra :: Uint8
gpsRawIntCrcExtra = 24

gpsRawIntModule :: Module
gpsRawIntModule = package "mavlink_gps_raw_int_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkGpsRawIntSender
  incl gpsRawIntUnpack
  defStruct (Proxy :: Proxy "gps_raw_int_msg")

[ivory|
struct gps_raw_int_msg
  { time_usec :: Stored Uint64
  ; lat :: Stored Sint32
  ; lon :: Stored Sint32
  ; alt :: Stored Sint32
  ; eph :: Stored Uint16
  ; epv :: Stored Uint16
  ; vel :: Stored Uint16
  ; cog :: Stored Uint16
  ; fix_type :: Stored Uint8
  ; satellites_visible :: Stored Uint8
  }
|]

mkGpsRawIntSender ::
  Def ('[ ConstRef s0 (Struct "gps_raw_int_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkGpsRawIntSender =
  proc "mavlink_gps_raw_int_msg_send"
  $ \msg seqNum sendStruct -> body
  $ do
  arr <- local (iarray [] :: Init (Array 30 (Stored Uint8)))
  let buf = toCArray arr
  pack buf 0 =<< deref (msg ~> time_usec)
  pack buf 8 =<< deref (msg ~> lat)
  pack buf 12 =<< deref (msg ~> lon)
  pack buf 16 =<< deref (msg ~> alt)
  pack buf 20 =<< deref (msg ~> eph)
  pack buf 22 =<< deref (msg ~> epv)
  pack buf 24 =<< deref (msg ~> vel)
  pack buf 26 =<< deref (msg ~> cog)
  pack buf 28 =<< deref (msg ~> fix_type)
  pack buf 29 =<< deref (msg ~> satellites_visible)
  -- 6: header len, 2: CRC len
  let usedLen    = 6 + 30 + 2 :: Integer
  let sendArr    = sendStruct ~> mav_array
  let sendArrLen = arrayLen sendArr
  if sendArrLen < usedLen
    then error "gpsRawInt payload of length 30 is too large!"
    else do -- Copy, leaving room for the payload
            arrayCopy sendArr arr 6 (arrayLen arr)
            call_ mavlinkSendWithWriter
                    gpsRawIntMsgId
                    gpsRawIntCrcExtra
                    30
                    seqNum
                    sendStruct

instance MavlinkUnpackableMsg "gps_raw_int_msg" where
    unpackMsg = ( gpsRawIntUnpack , gpsRawIntMsgId )

gpsRawIntUnpack :: Def ('[ Ref s1 (Struct "gps_raw_int_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
gpsRawIntUnpack = proc "mavlink_gps_raw_int_unpack" $ \ msg buf -> body $ do
  store (msg ~> time_usec) =<< unpack buf 0
  store (msg ~> lat) =<< unpack buf 8
  store (msg ~> lon) =<< unpack buf 12
  store (msg ~> alt) =<< unpack buf 16
  store (msg ~> eph) =<< unpack buf 20
  store (msg ~> epv) =<< unpack buf 22
  store (msg ~> vel) =<< unpack buf 24
  store (msg ~> cog) =<< unpack buf 26
  store (msg ~> fix_type) =<< unpack buf 28
  store (msg ~> satellites_visible) =<< unpack buf 29

