{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.HilState where

import Ivory.Serialize
import SMACCMPilot.Mavlink.Unpack
import SMACCMPilot.Mavlink.Send

import Ivory.Language
import Ivory.Stdlib

hilStateMsgId :: Uint8
hilStateMsgId = 90

hilStateCrcExtra :: Uint8
hilStateCrcExtra = 183

hilStateModule :: Module
hilStateModule = package "mavlink_hil_state_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkHilStateSender
  incl hilStateUnpack
  defStruct (Proxy :: Proxy "hil_state_msg")

[ivory|
struct hil_state_msg
  { time_usec :: Stored Uint64
  ; roll :: Stored IFloat
  ; pitch :: Stored IFloat
  ; yaw :: Stored IFloat
  ; rollspeed :: Stored IFloat
  ; pitchspeed :: Stored IFloat
  ; yawspeed :: Stored IFloat
  ; lat :: Stored Sint32
  ; lon :: Stored Sint32
  ; alt :: Stored Sint32
  ; vx :: Stored Sint16
  ; vy :: Stored Sint16
  ; vz :: Stored Sint16
  ; xacc :: Stored Sint16
  ; yacc :: Stored Sint16
  ; zacc :: Stored Sint16
  }
|]

mkHilStateSender ::
  Def ('[ ConstRef s0 (Struct "hil_state_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkHilStateSender =
  proc "mavlink_hil_state_msg_send"
  $ \msg seqNum sendStruct -> body
  $ do
  arr <- local (iarray [] :: Init (Array 56 (Stored Uint8)))
  let buf = toCArray arr
  pack buf 0 =<< deref (msg ~> time_usec)
  pack buf 8 =<< deref (msg ~> roll)
  pack buf 12 =<< deref (msg ~> pitch)
  pack buf 16 =<< deref (msg ~> yaw)
  pack buf 20 =<< deref (msg ~> rollspeed)
  pack buf 24 =<< deref (msg ~> pitchspeed)
  pack buf 28 =<< deref (msg ~> yawspeed)
  pack buf 32 =<< deref (msg ~> lat)
  pack buf 36 =<< deref (msg ~> lon)
  pack buf 40 =<< deref (msg ~> alt)
  pack buf 44 =<< deref (msg ~> vx)
  pack buf 46 =<< deref (msg ~> vy)
  pack buf 48 =<< deref (msg ~> vz)
  pack buf 50 =<< deref (msg ~> xacc)
  pack buf 52 =<< deref (msg ~> yacc)
  pack buf 54 =<< deref (msg ~> zacc)
  -- 6: header len, 2: CRC len
  let usedLen    = 6 + 56 + 2 :: Integer
  let sendArr    = sendStruct ~> mav_array
  let sendArrLen = arrayLen sendArr
  if sendArrLen < usedLen
    then error "hilState payload of length 56 is too large!"
    else do -- Copy, leaving room for the payload
            arrayCopy sendArr arr 6 (arrayLen arr)
            call_ mavlinkSendWithWriter
                    hilStateMsgId
                    hilStateCrcExtra
                    56
                    seqNum
                    sendStruct

instance MavlinkUnpackableMsg "hil_state_msg" where
    unpackMsg = ( hilStateUnpack , hilStateMsgId )

hilStateUnpack :: Def ('[ Ref s1 (Struct "hil_state_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
hilStateUnpack = proc "mavlink_hil_state_unpack" $ \ msg buf -> body $ do
  store (msg ~> time_usec) =<< unpack buf 0
  store (msg ~> roll) =<< unpack buf 8
  store (msg ~> pitch) =<< unpack buf 12
  store (msg ~> yaw) =<< unpack buf 16
  store (msg ~> rollspeed) =<< unpack buf 20
  store (msg ~> pitchspeed) =<< unpack buf 24
  store (msg ~> yawspeed) =<< unpack buf 28
  store (msg ~> lat) =<< unpack buf 32
  store (msg ~> lon) =<< unpack buf 36
  store (msg ~> alt) =<< unpack buf 40
  store (msg ~> vx) =<< unpack buf 44
  store (msg ~> vy) =<< unpack buf 46
  store (msg ~> vz) =<< unpack buf 48
  store (msg ~> xacc) =<< unpack buf 50
  store (msg ~> yacc) =<< unpack buf 52
  store (msg ~> zacc) =<< unpack buf 54

