{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.LocalPositionNedSystemGlobalOffset where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Send
import SMACCMPilot.Mavlink.Unpack

localPositionNedSystemGlobalOffsetMsgId :: Uint8
localPositionNedSystemGlobalOffsetMsgId = 89

localPositionNedSystemGlobalOffsetCrcExtra :: Uint8
localPositionNedSystemGlobalOffsetCrcExtra = 231

localPositionNedSystemGlobalOffsetModule :: Module
localPositionNedSystemGlobalOffsetModule = package "mavlink_local_position_ned_system_global_offset_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkLocalPositionNedSystemGlobalOffsetSender
  incl localPositionNedSystemGlobalOffsetUnpack
  defStruct (Proxy :: Proxy "local_position_ned_system_global_offset_msg")
  incl localPositionNedSystemGlobalOffsetPackRef
  incl localPositionNedSystemGlobalOffsetUnpackRef

[ivory|
struct local_position_ned_system_global_offset_msg
  { time_boot_ms :: Stored Uint32
  ; x :: Stored IFloat
  ; y :: Stored IFloat
  ; z :: Stored IFloat
  ; roll :: Stored IFloat
  ; pitch :: Stored IFloat
  ; yaw :: Stored IFloat
  }
|]

mkLocalPositionNedSystemGlobalOffsetSender ::
  Def ('[ ConstRef s0 (Struct "local_position_ned_system_global_offset_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkLocalPositionNedSystemGlobalOffsetSender = makeMavlinkSender "local_position_ned_system_global_offset_msg" localPositionNedSystemGlobalOffsetMsgId localPositionNedSystemGlobalOffsetCrcExtra

instance MavlinkUnpackableMsg "local_position_ned_system_global_offset_msg" where
    unpackMsg = ( localPositionNedSystemGlobalOffsetUnpack , localPositionNedSystemGlobalOffsetMsgId )

localPositionNedSystemGlobalOffsetUnpack :: Def ('[ Ref s1 (Struct "local_position_ned_system_global_offset_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
localPositionNedSystemGlobalOffsetUnpack = proc "mavlink_local_position_ned_system_global_offset_unpack" $ \ msg buf -> body $ unpackRef buf 0 msg

localPositionNedSystemGlobalOffsetPackRef :: Def ('[ Ref s1 (CArray (Stored Uint8))
                              , Uint32
                              , ConstRef s2 (Struct "local_position_ned_system_global_offset_msg")
                              ] :-> () )
localPositionNedSystemGlobalOffsetPackRef = proc "mavlink_local_position_ned_system_global_offset_pack_ref" $ \ buf off msg -> body $ do
  packRef buf (off + 0) (msg ~> time_boot_ms)
  packRef buf (off + 4) (msg ~> x)
  packRef buf (off + 8) (msg ~> y)
  packRef buf (off + 12) (msg ~> z)
  packRef buf (off + 16) (msg ~> roll)
  packRef buf (off + 20) (msg ~> pitch)
  packRef buf (off + 24) (msg ~> yaw)

localPositionNedSystemGlobalOffsetUnpackRef :: Def ('[ ConstRef s1 (CArray (Stored Uint8))
                                , Uint32
                                , Ref s2 (Struct "local_position_ned_system_global_offset_msg")
                                ] :-> () )
localPositionNedSystemGlobalOffsetUnpackRef = proc "mavlink_local_position_ned_system_global_offset_unpack_ref" $ \ buf off msg -> body $ do
  unpackRef buf (off + 0) (msg ~> time_boot_ms)
  unpackRef buf (off + 4) (msg ~> x)
  unpackRef buf (off + 8) (msg ~> y)
  unpackRef buf (off + 12) (msg ~> z)
  unpackRef buf (off + 16) (msg ~> roll)
  unpackRef buf (off + 20) (msg ~> pitch)
  unpackRef buf (off + 24) (msg ~> yaw)

instance SerializableRef (Struct "local_position_ned_system_global_offset_msg") where
  packRef = call_ localPositionNedSystemGlobalOffsetPackRef
  unpackRef = call_ localPositionNedSystemGlobalOffsetUnpackRef
