{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.MissionCount where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Send
import SMACCMPilot.Mavlink.Unpack

missionCountMsgId :: Uint8
missionCountMsgId = 44

missionCountCrcExtra :: Uint8
missionCountCrcExtra = 221

missionCountModule :: Module
missionCountModule = package "mavlink_mission_count_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkMissionCountSender
  incl missionCountUnpack
  defStruct (Proxy :: Proxy "mission_count_msg")
  incl missionCountPackRef
  incl missionCountUnpackRef

[ivory|
struct mission_count_msg
  { count :: Stored Uint16
  ; target_system :: Stored Uint8
  ; target_component :: Stored Uint8
  }
|]

mkMissionCountSender ::
  Def ('[ ConstRef s0 (Struct "mission_count_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkMissionCountSender = makeMavlinkSender "mission_count_msg" missionCountMsgId missionCountCrcExtra

instance MavlinkUnpackableMsg "mission_count_msg" where
    unpackMsg = ( missionCountUnpack , missionCountMsgId )

missionCountUnpack :: Def ('[ Ref s1 (Struct "mission_count_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
missionCountUnpack = proc "mavlink_mission_count_unpack" $ \ msg buf -> body $ unpackRef buf 0 msg

missionCountPackRef :: Def ('[ Ref s1 (CArray (Stored Uint8))
                              , Uint32
                              , ConstRef s2 (Struct "mission_count_msg")
                              ] :-> () )
missionCountPackRef = proc "mavlink_mission_count_pack_ref" $ \ buf off msg -> body $ do
  packRef buf (off + 0) (msg ~> count)
  packRef buf (off + 2) (msg ~> target_system)
  packRef buf (off + 3) (msg ~> target_component)

missionCountUnpackRef :: Def ('[ ConstRef s1 (CArray (Stored Uint8))
                                , Uint32
                                , Ref s2 (Struct "mission_count_msg")
                                ] :-> () )
missionCountUnpackRef = proc "mavlink_mission_count_unpack_ref" $ \ buf off msg -> body $ do
  unpackRef buf (off + 0) (msg ~> count)
  unpackRef buf (off + 2) (msg ~> target_system)
  unpackRef buf (off + 3) (msg ~> target_component)

instance SerializableRef (Struct "mission_count_msg") where
  packRef = call_ missionCountPackRef
  unpackRef = call_ missionCountUnpackRef
