{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE MultiParamTypeClasses #-}

-- Autogenerated Mavlink v1.0 implementation: see smavgen_ivory.py

module SMACCMPilot.Mavlink.Messages.SafetyAllowedArea where

import Ivory.Language
import Ivory.Serialize
import SMACCMPilot.Mavlink.Send
import SMACCMPilot.Mavlink.Unpack

safetyAllowedAreaMsgId :: Uint8
safetyAllowedAreaMsgId = 55

safetyAllowedAreaCrcExtra :: Uint8
safetyAllowedAreaCrcExtra = 3

safetyAllowedAreaModule :: Module
safetyAllowedAreaModule = package "mavlink_safety_allowed_area_msg" $ do
  depend serializeModule
  depend mavlinkSendModule
  incl mkSafetyAllowedAreaSender
  incl safetyAllowedAreaUnpack
  defStruct (Proxy :: Proxy "safety_allowed_area_msg")
  incl safetyAllowedAreaPackRef
  incl safetyAllowedAreaUnpackRef

[ivory|
struct safety_allowed_area_msg
  { p1x :: Stored IFloat
  ; p1y :: Stored IFloat
  ; p1z :: Stored IFloat
  ; p2x :: Stored IFloat
  ; p2y :: Stored IFloat
  ; p2z :: Stored IFloat
  ; frame :: Stored Uint8
  }
|]

mkSafetyAllowedAreaSender ::
  Def ('[ ConstRef s0 (Struct "safety_allowed_area_msg")
        , Ref s1 (Stored Uint8) -- seqNum
        , Ref s1 (Struct "mavlinkPacket") -- tx buffer/length
        ] :-> ())
mkSafetyAllowedAreaSender = makeMavlinkSender "safety_allowed_area_msg" safetyAllowedAreaMsgId safetyAllowedAreaCrcExtra

instance MavlinkUnpackableMsg "safety_allowed_area_msg" where
    unpackMsg = ( safetyAllowedAreaUnpack , safetyAllowedAreaMsgId )

safetyAllowedAreaUnpack :: Def ('[ Ref s1 (Struct "safety_allowed_area_msg")
                             , ConstRef s2 (CArray (Stored Uint8))
                             ] :-> () )
safetyAllowedAreaUnpack = proc "mavlink_safety_allowed_area_unpack" $ \ msg buf -> body $ unpackRef buf 0 msg

safetyAllowedAreaPackRef :: Def ('[ Ref s1 (CArray (Stored Uint8))
                              , Uint32
                              , ConstRef s2 (Struct "safety_allowed_area_msg")
                              ] :-> () )
safetyAllowedAreaPackRef = proc "mavlink_safety_allowed_area_pack_ref" $ \ buf off msg -> body $ do
  packRef buf (off + 0) (msg ~> p1x)
  packRef buf (off + 4) (msg ~> p1y)
  packRef buf (off + 8) (msg ~> p1z)
  packRef buf (off + 12) (msg ~> p2x)
  packRef buf (off + 16) (msg ~> p2y)
  packRef buf (off + 20) (msg ~> p2z)
  packRef buf (off + 24) (msg ~> frame)

safetyAllowedAreaUnpackRef :: Def ('[ ConstRef s1 (CArray (Stored Uint8))
                                , Uint32
                                , Ref s2 (Struct "safety_allowed_area_msg")
                                ] :-> () )
safetyAllowedAreaUnpackRef = proc "mavlink_safety_allowed_area_unpack_ref" $ \ buf off msg -> body $ do
  unpackRef buf (off + 0) (msg ~> p1x)
  unpackRef buf (off + 4) (msg ~> p1y)
  unpackRef buf (off + 8) (msg ~> p1z)
  unpackRef buf (off + 12) (msg ~> p2x)
  unpackRef buf (off + 16) (msg ~> p2y)
  unpackRef buf (off + 20) (msg ~> p2z)
  unpackRef buf (off + 24) (msg ~> frame)

instance SerializableRef (Struct "safety_allowed_area_msg") where
  packRef = call_ safetyAllowedAreaPackRef
  unpackRef = call_ safetyAllowedAreaUnpackRef
