# -*- Mode: makefile-gmake; indent-tabs-mode: t; tab-width: 2 -*-
#
# build.mk --- Build rules for the ArduCopter program.
#
# Copyright (C) 2012, Galois, Inc.
# All Rights Reserved.
#
# Written by James Bielman <jamesjb@galois.com>, December 07, 2012
#

ARDUCOPTER_SKETCH         := ArduCopter
ARDUCOPTER_SKETCH_CPP     := $(TOP)/src/flight-support/ardupilot/$(ARDUCOPTER_SKETCH)/sketch.cpp
ARDUCOPTER_SRC            := $(CONFIG_ARDUPILOT_PREFIX)/$(ARDUCOPTER_SKETCH)

ARDUCOPTER_SKETCH_SOURCES := $(wildcard $(ARDUCOPTER_SRC)/*.pde)
ARDUCOPTER_SKETCH_SOURCES += $(wildcard $(ARDUCOPTER_SRC)/*.ino)
ARDUCOPTER_SKETCH_PDE     := $(wildcard $(ARDUCOPTER_SRC)/$(ARDUCOPTER_SKETCH).pde)
ARDUCOPTER_SKETCH_PDE     += $(wildcard $(ARDUCOPTER_SRC)/$(ARDUCOPTER_SKETCH).ino)
ARDUCOPTER_SKETCH_CPP     := $(TOP)/src/flight-support/ardupilot/$(ARDUCOPTER_SKETCH)/$(ARDUCOPTER_SKETCH).cpp

ARDUCOPTER_SKETCH_CPP_SRC := $(ARDUCOPTER_SKETCH_PDE)
ARDUCOPTER_SKETCH_CPP_SRC += $(sort $(filter-out $(ARDUCOPTER_SKETCH_PDE),\
                                                 $(ARDUCOPTER_SKETCH_SOURCES)))

ARDUCOPTER_IMG      := ArduCopter
ARDUCOPTER_OBJECTS  := ArduCopter.o
ARDUCOPTER_CXXFLAGS  = -I$(ARDUCOPTER_SRC)
ARDUCOPTER_CXXFLAGS += $(ARDUPILOT_CXXFLAGS)
ARDUCOPTER_CXXFLAGS += -Wno-unused-function
ARDUCOPTER_CXXFLAGS += -I$(TOP)/src/bsp/include
ARDUCOPTER_CFLAGS   += -I$(TOP)/src/bsp/include

ARDUCOPTER_LIBRARIES += libardupilot.a
ARDUCOPTER_LIBRARIES += libhwf4.a
ARDUCOPTER_LIBRARIES += libstm32_usb.a
ARDUCOPTER_LIBRARIES += libFreeRTOS.a

ARDUCOPTER_LIBS += -lm

$(ARDUCOPTER_SKETCH_CPP): $(ARDUCOPTER_SKETCH_CPP_SRC)
	gawk -v mode=header -f $(TOP)/flight-support/ardupilot/mk/splitter.awk $(ARDUCOPTER_SKETCH_CPP_SRC) >  $@
	echo "#line 1 \"autogenerated\""                                                    >> $@
	gawk -f $(TOP)/flight-support/ardupilot/mk/prototyper.awk $(ARDUCOPTER_SKETCH_CPP_SRC)              >> $@
	gawk -v mode=body -f $(TOP)/flight-support/ardupilot/mk/splitter.awk $(ARDUCOPTER_SKETCH_CPP_SRC)   >> $@

.DELETE_ON_ERROR: $(ARDUCOPTER_SKETCH_CPP)

ifdef CONFIG_ARDUPILOT_PREFIX
$(eval $(call image,ARDUCOPTER))
endif

# vim: set ft=make noet ts=2:
